name: CI/CD – Build & Publish Docker Image

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: latest
      DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      # Variable ECR: Debe coincidir con el repositorio creado en AWS
      ECR_REPOSITORY_NAME: proyectobase-runtime
      
    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🔖 Determine version tag
        id: version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "VERSION=latest" >> $GITHUB_ENV
          fi

      - name: 🛠️ Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧪 Run tests
        run: npm run test

      # Configuración de Docker Buildx
      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      # --- AUTENTICACIÓN AWS y LOGIN ECR ---
      
      - name: ⚙️ Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # Es CRÍTICO que el IAM User usado aquí tenga permisos para:
          # 1. Acceder a ECR (ecr:*)
          # 2. Actualizar ECS (ecs:UpdateService)
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: 🐳 Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        
      # --- LOGIN DOCKER HUB ---
      
      - name: 🐳 Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # --- CONSTRUCCIÓN Y PUSH DUAL ---
      
      # 🔨 BUILDER IMAGE (Push SOLO a Docker Hub)
      - name: 🔨 Build & Push BUILDER image (Docker Hub Only)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: builder
          push: true
          tags: |
            ${{ env.DOCKER_USER }}/proyectobase-builder:${{ env.VERSION }}
            ${{ env.DOCKER_USER }}/proyectobase-builder:latest

      # ⚙️ RUNTIME IMAGE (Construcción Única y Push Dual a Docker Hub y ECR)
      - name: ⚙️ Build & Push RUNTIME image (Dual Push)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: production
          push: true
          tags: |
            ${{ env.DOCKER_USER }}/proyectobase-runtime:${{ env.VERSION }}
            ${{ env.DOCKER_USER }}/proyectobase-runtime:latest
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_NAME }}:${{ env.VERSION }}
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_NAME }}:latest

      - name: 🧹 Clean up dangling images
        run: docker image prune -f

      # --- 🚀 PASO NUEVO: DEPLOY A ECS (CD) ---
      - name: 🚀 Force New Deployment on ECS Service
        run: |
          echo "Deploying new image to ECS..."
          aws ecs update-service \
            --cluster frontend-cluster \
            --service frontend-service \
            --force-new-deployment \
            --region ${{ secrets.AWS_REGION }}
          echo "Deployment initiated. ECS will now pull the latest image from ECR."